pipeline {
    agent any

    stages {
        stage("Install") {
            steps {
                sh 'cd app && npm ci'
            }
        }

        stage("Qualité") {
            parallel {

                stage("Lint") {
                    steps {
                        sh "cd app && npm run lint"
                    }

                }
                stage("Tests") {
                    steps {
                        sh "cd app && npm run test:coverage"
                    }
                }
            }
        }

        stage {
          steps {
            sh "docker build -t node-app:latest"
          }
        }
    }
}