pipeline {
  agent any

  stages {
      stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Install') {
      steps {
        sh 'npm ci'
      }

      stage('Lint') {
        steps {
          sh 'npm run lint'
        }
      }
      stage('Test') {
        steps {
          sh 'npm run test:coverage'
        }
      }
    }
  }
}